import { Navbar } from '@/components';
import './globals.css';

export const metadata = {
  title: 'Travel',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;0,900;1,400&family=Nunito:ital,wght@0,300;0,400;0,600;0,700;0,800;0,900;1,500&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
